### ISSUE TITLE
Star dissapears when over inactive buttons 

### ISSUE THREAD

**Issue by Oakheart27** [SciKids/GestureBasedSystem#9]
Star has dissapearing graphic when user drops it over continue button despite button being inactive. Stops game progress as star doesn't reset and desktop mode must be used 
-Have check for if button inactive and stop star.

**Comment by SammieJ201** [comment]
Added an extra condition for the star to toggle the onclick function (line 50 in MoveStarV2).
![image](https://user-images.githubusercontent.com/33239649/73698653-feb0d400-469e-11ea-80ec-6837d8a97389.png)
